version: "3"

services:
  db:
    platform: linux/x86_64 # 추가된 라인
    image: mysql:5.7
    volumes:
      - "./db/data:/var/lib/mysql:rw"
    environment:
      - "MYSQL_DATABASE=hello"
      - "MYSQL_USER=hello"
      - "MYSQL_PASSWORD=hello"
      - "MYSQL_ROOT_PASSWORD=root"
    ports:
      - "3306:3306"
  phpmyadmin:
    platform: linux/x86_64 # 추가된 라인
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      - "PMA_HOST=db"
      - "PMA_USER=root"
      - "PMA_PASSWORD=root"
  web:
    platform: linux/x86_64 # 추가된 라인
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ".:/var/www/html"
    depends_on:
      - db
    ports:
      - "80:80"
